### ISSUE TITLE
Memory leak with Hystrix Timer

### ISSUE THREAD

**Issue by renjith7189** [Netflix/Hystrix#1431] opened 2016-11-28 12:06 UTC
We have three backend services which are exposed via restapi. The responses from all the three are zipped into an Observable.
return Observable.zip(api1,
				api2,
				api3,

Whenever there is any problem with any of the micro service, the heap usage is going very high suddenly. May be timer is not releasing the observables when there is error with any of the services.
[Heap_walker_Biggest_objects.xml.zip](https://github.com/Netflix/Hystrix/files/616185/Heap_walker_Biggest_objects.xml.zip)

**Comment by renjith7189** [comment] 2016-11-28 12:07
@mattrjacobs Could you please confirm is it similar to #1370 ?

**Comment by mattrjacobs** [comment] 2016-11-28 22:37
The symptoms are similar.  What version are you using?  If you're on the latest release, then it's different, since the root cause of #1370 has already been fixed and released.

**Comment by renjith7189** [comment] 2016-11-29 11:20
We are using the older version.
RxJava 1.0.10
Hystrix 1.4.3

**Comment by mattrjacobs** [comment] 2016-12-02 23:32
Yes, upgrading has a good chance of resolving your problem.

**Closed** 2016-12-21 07:57 UTC
Labels: question
