### ISSUE TITLE
Hystrix Javanica not wrapping any exceptions

### ISSUE THREAD

**Issue by smjdowling** [Netflix/Hystrix#1285] opened 2016-07-20 10:12 UTC
Steps to reproduce:
In a HystrixCommand throw a new exception

Expected: 
Exceptions should be wrapped in HystrixRuntimeException or HystrixBadRequestException (if ignored). 

Actual: 
The exception isn't wrapped -- the thrown exception is propagated instead of a wrapped exception.

**Comment by smjdowling** [comment] 2016-07-20 10:13
related to https://github.com/Netflix/Hystrix/pull/1273

**Comment by mattrjacobs** [comment] 2016-07-22 18:43
Is this in master, or in a released version of Hystrix?

**Comment by smjdowling** [comment] 2016-07-25 08:50
@mattrjacobs this is in master after testing the changes from this pr https://github.com/Netflix/Hystrix/pull/1273. Thanks.

**Comment by jbojar** [comment] 2016-08-02 14:04
@smjdowling Are you sure that exceptions should be wrapped if using HystrixCommandAspect from javanica? Unwrapping from HystrixRuntimeException was added in HystrixCommandAspect in commit 155d4e97a2d019238c939fd074feb9443e09ab68 and unwrapping from HystrixBadRequestException even earlier in commit 59bbe9f584b50ef7f12909e460c7c9415e8618c9.

**Comment by dmgcodevil** [comment] 2016-08-09 03:25
hi, @smjdowling , @jbojar thanks for the answer, yes, I removed the logic to wrap original exceptions in corresponding hystrix exceptions, because throwing hystrix exceptions makes error handling awkward in spring framework. see [iss993](https://github.com/Netflix/Hystrix/issues/993)

**Comment by michaelcowan** [comment] 2016-09-13 12:38
I understand the idea of making Javanica as transparent as possible, however personally I prefer keeping Javanica thin and not assume anything e.g. in my case we relied on knowing if an exception was ignored or not further up the stack. It was used in error reporting and also allowed us to monitor for unexpected exception being treated as errors that shouldn't be.

What concerns me more than my preference though, is that I can't see how the tests can possibly be testing `ignoreExceptions`. If an exception is ignored, then expected is that exception. If an exception is not ignored, then expected used to be `HystrixRuntimeException` but is now that exception. There is no difference. (See [BasicDefaultIgnoreExceptionsTest.java](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/common/error/BasicDefaultIgnoreExceptionsTest.java#L26))

**Comment by dmgcodevil** [comment] 2016-09-13 13:45
@michaelcowan , regarding ignored exceptions. Yes it's expected behaviour to get user exception regardless whether it's ignored or not. Throwing hystrix exceptions is pointless for most users. To test ignored exceptions you should check command metrics/events to verify that fallback wasn't triggered. It's easy to do. The whole point of javanica is making your code doesn't depend on hystrix platform so that you can change this lib in the future without changing your code. Throwing platform specific exceptions is kind of leaking abstraction.

**Comment by michaelcowan** [comment] 2016-09-13 14:17
@dmgcodevil I totally see where you are coming from. It is much more elegant and hugely simplified for most users - its just that now this is the _only_ way. For me personally Javanica was simply a convenient way to integrate Hystrix without having to hand roll lots of command classes.

How would you feel about something like [this](https://github.com/Netflix/Hystrix/compare/master...michaelcowan:feature/optionally-raise-hystrix-runtime-exception?expand=1)?

Were you suggesting to check the command events in a unit test? How would you go about this?

**Comment by dmgcodevil** [comment] 2016-09-13 14:30
@michaelcowan I'll take a look and answer latter

**Comment by dmgcodevil** [comment] 2016-09-14 02:21
@michaelcowan let's continue discussion [here ](https://github.com/Netflix/Hystrix/issues/1344)

**Comment by mattrjacobs** [comment] 2016-12-21 07:58
I think this has been closed by PRs since this issue was raised.  If there are still open questions, please re-open.

**Closed by mattrjacobs** 2016-12-21 07:58 UTC
Labels: javanica
