### ISSUE TITLE
Javanica threadpool properties per class are applied to all thread pools

### ISSUE THREAD

**Issue by john-roj87** [Netflix/Hystrix#926] opened 2015-10-09 18:26 UTC
On our project we have 2 classes Annotated with ```@HystrixCommand```

```
public class SomeService {
       
     @HystrixCommand(
        ignoreExceptions = { NonSevereClientException.class },
        commandProperties = {
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = 5000)
        },
        threadPoolProperties = {
            @HystrixProperty(name = "coreSize", value = 75,
            @HystrixProperty(name = "maxQueueSize", value = 5)
        })
        public Response getAll(Long someParam) {}  ...
```

The other class uses defaults for thread pool properties:

```
public class SomeOtherService {
       
     @HystrixCommand(
        ignoreExceptions = { NonSevereClientException.class },
        commandProperties = {
            @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = 5000)
        }
        public Response getStuff() {}  ...
```
However when we check the Dashboard both thread pools have poolSize set to 75.

<img width="467" alt="screen shot 2015-10-09 at 11 23 37 am" src="https://cloud.githubusercontent.com/assets/4062524/10402145/799cee5a-6e78-11e5-850f-f9d0dc678df7.png">

Is this expected?

**Comment by dmgcodevil** [comment] 2015-10-09 19:26
Hi, 
I don't think that it's correct behavior, could you try to specify specific thread pool name using threadPoolKey property of HystrixCommand annotation and see what happen ?

```java
@HystrixCommand(threadPoolKey="thp1")
public Response getAll(Long someParam) {} 

@HystrixCommand(threadPoolKey="thp2")
public Response getStuff() {} 

```

Thanks

**Comment by john-roj87** [comment] 2015-10-09 22:01
Well adding the threadPoolKey seems to have worked... I am wondering if it is indeed a bug and this is a workaround.

Thanks

**Comment by dmgcodevil** [comment] 2015-10-10 15:49
it looks like a bug, currently I'm working on #907 bug and at the same time will check this one

**Comment by dmgcodevil** [comment] 2015-10-14 23:55
Actually we have the tests to check command properties including threadPoolKey and it works well: [test](https://github.com/Netflix/Hystrix/blob/master/hystrix-contrib/hystrix-javanica/src/test/java/com/netflix/hystrix/contrib/javanica/test/spring/configuration/command/CommandPropertiesTest.java), I've added more tests but failed to reproduce the issue.
@john-roj87 what javanica version are you using, also could you write a test that reproduces the issue ?

**Comment by dmgcodevil** [comment] 2015-10-15 21:41
Ok, I found root cause of the issue, actually it's the same for #782 and should be fixed altogether

**Comment by dmgcodevil** [comment] 2015-11-04 13:04
@mattrjacobs hi, you can close it

**Closed** 2015-11-04 13:07 UTC
Labels: bug, javanica
