### ISSUE TITLE
Hystrix using archaius-core instead of archaius2-core

### ISSUE THREAD

**Issue by martosoler** [Netflix/Hystrix#1395] opened 2016-10-19 19:37 UTC
I'm making a POC of Netflix Hystrix in our project and I received this exception:

`java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/NestableRuntimeException`

This class belongs to commons-lang-2.6 jar but in our project we are using comons-lang3-3.4.
By other hand, archaius-core depends on commons-lang-2.6 but the second version (archaius2-core) depends on commons-lang3.

Is there any plan to release a version of Hystrix which depends on archaius2-core?

Thanks

**Comment by mattrjacobs** [comment] 2016-10-19 20:00
We do eventually plan to get Hystrix working with Archaius2, but have not had cycles to do this work.  See #252.  This ends up being quite a large change, as some Archaius1 classes are exposed as public, so this necessitates a Hystrix 2.0 release.

**Comment by martosoler** [comment] 2016-10-19 20:05
So, basically what you're saying is that I need to stick to commons-lang-2.6 if I want to use Hystrix?

I was able to make it working with archaius2-core by just dropping the right jars but I think this won't be acceptable in our project.

Thanks for the quick response

**Comment by mattrjacobs** [comment] 2016-10-21 20:22
I don't know how hard the dependency of Archaius is on commons-lang, but I suspect pinning commons-lang to 2.6 should work.

**Comment by mattrjacobs** [comment] 2016-10-26 21:50
Closing this, as it's a duplicate of #252

**Closed by mattrjacobs** 2016-10-26 21:50 UTC
Labels: duplicate, hystrix-core
