### ISSUE TITLE
Thread Interruption on time doesn't work for doExecute() in javanica

### ISSUE THREAD

**Issue by VaultB0Y** [Netflix/Hystrix#1321] opened 2016-08-16 21:14 UTC
Hi guys I am now introducing Hystrix  Javanica in our project. Our project use Spring, so I am trying to wrap HystrixCommand in RestTemplate. I have tried to annotate getForObject() and doExecute() with HystrixCommand. What I expect that is when the call exceeds the timeoutInMilliseconds, the thread will be interrupted and handled by fallback. It's strange that the getForObject() is working as expected, but the doExecute() doesn't work. The doExecute will not be interrupted and so the "doExecuteFallback" will not be printed. 
In the Srping RestTemplate, the exchange(), getForObject() and getForEntity() will finally call doExecute(). 

```
public class HystrixCircuitBreakerRestTemplate extends RestTemplate {
    @Override
    @HystrixCommand(fallbackMethod = "doExecuteFallback", 
    commandProperties = { 
        @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "10"),
        @HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "10000"),
        @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "3"),
        @HystrixProperty(name = "circuitBreaker.errorThresholdPercentage", value = "10"),
    }) 
    protected <T> T doExecute(URI url, HttpMethod method, RequestCallback requestCallback,
			ResponseExtractor<T> responseExtractor) throws RestClientException {
    	System.out.println("doExecute");
    	long startTime = new Date().getTime();
        T response = super.doExecute(url, method, requestCallback, responseExtractor);
        long endTime = new Date().getTime();
        System.out.println("doExecute: " + (endTime - startTime));
        return response;
    }
    
    protected <T> T doExecuteFallback(URI url, HttpMethod method, RequestCallback requestCallback,
			ResponseExtractor<T> responseExtractor) throws RestClientException {
    	System.out.println("doExecuteFallback");
        return null;
    }
	
    @Override
    @HystrixCommand(fallbackMethod = "getForObjectFallback", 
    commandProperties = { 
        @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "150"),
        @HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "10000"),
        @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "3"),
        @HystrixProperty(name = "circuitBreaker.errorThresholdPercentage", value = "10")
    }) 
	public <T> T getForObject(String url, Class<T> responseType, Object... urlVariables) throws RestClientException {
		System.out.println("HystrixCircuitBreakerRestTemplate: getForEntity");
		return super.getForObject(url, responseType, urlVariables);
	}
	
	public <T> T getForObjectFallback(String url, Class<T> responseType, Object... urlVariables) throws RestClientException {
		System.out.println("HystrixCircuitBreakerRestTemplate: Fallback");
		return null;
    }
```

**Comment by spencergibb** [comment] 2016-08-17 00:07
Not the right repo for this issue (spring-cloud-netflix). `@HystrixCommand` is AOP and doesn't work calling internal methods.

**Comment by VaultB0Y** [comment] 2016-08-18 00:16
Thanks for your answer Spencer, it really helps. Looks like I need to add HystrixCommand to External methods. 

Now there is one more problem. I tried to add the hystrix command to getForEntity, but it throws an exception:

```
com.netflix.hystrix.contrib.javanica.exception.FallbackDefinitionException: Incompatible return types. Command method: public org.springframework.http.ResponseEntity hystrix.HystrixCircuitBreakerRestTemplate.getForEntity(java.lang.String,java.lang.Class,java.lang.Object[]) throws org.springframework.web.client.RestClientException, fallback method: public org.springframework.http.ResponseEntity hystrix.HystrixCircuitBreakerRestTemplate.getForEntityFallback(java.lang.String,java.lang.Class,java.lang.Object[]) throws org.springframework.web.client.RestClientException. Hint: 
	at com.netflix.hystrix.contrib.javanica.utils.FallbackMethod.validateReturnType(FallbackMethod.java:132)
	at com.netflix.hystrix.contrib.javanica.utils.FallbackMethod.validateReturnType(FallbackMethod.java:111)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.setFallbackMethod(HystrixCommandAspect.java:292)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.access$300(HystrixCommandAspect.java:62)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$MetaHolderFactory.metaHolderBuilder(HystrixCommandAspect.java:155)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$CommandMetaHolderFactory.create(HystrixCommandAspect.java:236)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect$MetaHolderFactory.create(HystrixCommandAspect.java:145)
	at com.netflix.hystrix.contrib.javanica.aop.aspectj.HystrixCommandAspect.methodsAnnotatedWithHystrixCommand(HystrixCommandAspect.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:644)
...

```

```
public class HystrixCircuitBreakerRestTemplate extends RestTemplate {
    @Override
    @HystrixCommand(fallbackMethod = "getForEntityFallback", 
    commandProperties = { 
        @HystrixProperty(name = "execution.isolation.thread.timeoutInMilliseconds", value = "10"),
        @HystrixProperty(name = "circuitBreaker.sleepWindowInMilliseconds", value = "10000"),
        @HystrixProperty(name = "circuitBreaker.requestVolumeThreshold", value = "3"),
        @HystrixProperty(name = "circuitBreaker.errorThresholdPercentage", value = "10"),
        @HystrixProperty(name = "circuitBreaker.forceOpen", value = "true")
    }) 
    public <T> ResponseEntity<T> getForEntity(String url, Class<T> responseType, Object... urlVariables) throws RestClientException {
    	System.out.println("HystrixCircuitBreakerRestTemplate: getForEntity");
    	return super.getForEntity(url, responseType, urlVariables);
    }
    
    public <T> ResponseEntity<T> getForEntityFallback(String url, Class<T> responseType, Object... urlVariables) throws RestClientException {
    	System.out.println("HystrixCircuitBreakerRestTemplate: Fallback");
    	return null;
    }
}
```


If I remove the fallbackMethod in the HystrixCommand, it is working fine. It doesn't work with the fallbackMethod. It's strange that the two return types are the same but throws incompatible return type exception.

**Comment by mattrjacobs** [comment] 2016-08-25 16:17
@VaultB0Y off the top of my head I would expect that to work as well.  Perhaps something about generics aren't working properly.  

@dmgcodevil - Are you able to take a look?

**Comment by mattrjacobs** [comment] 2016-08-25 16:21
Looks like this is a duplicate of #1328.  Let's continue the discussion there

**Closed by mattrjacobs** 2016-08-25 16:21 UTC
Labels: duplicate, javanica, question
