### ISSUE TITLE
Hung HystrixMetricsStreamServlet thread

### ISSUE THREAD

**Issue by santoshavkr** [Netflix/Hystrix#1346] opened 2016-09-07 05:55 UTC
HystrixMetricsStreamServlet execution is taking longer time and weblogic server is reporting it as struck thread.I cannot ignore set IGNORE STRUCK THREADS at weblogic as it ignores any other struck threads in the application.
Any suggestions on this .

**Comment by mukteshkrmishra** [comment] 2016-09-07 07:41
I faced the similiar issues and did following:
In web.xml include dependency on a work manager for hystrix call and then create this WM with “Ignore Stuck Threads” set to true.
 
<servlet>
        <display-name>HystrixMetricsStreamServlet</display-name>
        <servlet-name>HystrixMetricsStreamServlet</servlet-name>
        <servlet-class>com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet</servlet-class>
        <init-param>
                        <param-name>wl-dispatch-policy</param-name>
                        <param-value>HystrixWM</param-value>
                </init-param>
    </servlet>

**Comment by mamaigubasty** [comment] 2016-09-14 23:31
Why do you want to ignore a thread which is running over 10 minutes?

**Comment by santoshavkr** [comment] 2016-09-15 00:22
@mamaigubasty 

"Normal" servlet threads perform a function and return
to the free pool relatively quickly under "normal" circumstances.  This
thread is running the Hystrix Metrics Stream Servlet which is a never
ending loop that returns data to the client, sleeps and then repeats the
process until the app or server is shutdown or the client disconnects.  If
the client disconnects the Metrics Stream Servlet will detect this, quit
the loop and the thread will be returned back to the free thread pool"

So weblogic going to warning is a kind of false alarm.

@mukteshkrmishra  Thanks for help.Can u also share your weblogic.xml configuration.I created a local WM but somehow other non  Hystrix Metrics Stream Servlet threads are also going to that WM.

**Comment by mattrjacobs** [comment] 2016-09-16 22:38
I don't have any WebLogic knowledge, so I don't have anything to add to the above.

**Comment by mamaigubasty** [comment] 2016-09-18 23:39
It would be interesting to see the stuck HystrixMetricsStreamServlet thread log record.

Something like this:

 <Error> <WebLogicServer> <BEA-000337> <[STUCK] ExecuteThread: '4' for queue: 'webl
ogic.kernel.Default (self-tuning)' has been busy for "600" seconds working on the request "Workmanager: default
 which is more than the configured time (StuckThreadMaxTime) of "60" seconds. Stack trace:
 java.lang.Thread.sleep(Native Method)

If the Metrics Stream Servlet is using the Work Manager thread pool it will be subject to two parameters:

Servers -> Some_Server -> Configuration -> Tuning -> Stuck Thread Max Time
Servers -> Some_Server -> Configuration -> Overload -> Max Stuck Thread Time

If a total of Stuck Thread Count threads become stuck, theoretically, the server transitions itself to a failed state. 

However, it never happens. for a simple reason: the default configuration of WLS 12c is Stuck Thread Count = 0, which means the server never transitions into FAILED server irrespective of the number of stuck threads. 
You will  see the FAILED state only when it is  set  to a positive number of threads.
To change the default the WebLogic Admin needs to change the setting. I never witnessed  such an activity.
Once the server transitions into FAILED, you can define if WLS should be shut down (and restarted by WLS nodemanager) or suspended.

The root cause of the stuck threads should be investigated in Production environment. 

The skill  with the following items is helpful in troubleshooting.  
1. What exactly causes a stuck thread? What state does a thread have to be in to be marked as stuck?
2. Can a stuck thread still do reasonable work?
3. Do stuck threads ever disappear? Can they be cleared somehow? Are they stuck forever?

**Closed** 2016-10-03 18:14 UTC
Labels: metrics
