### ISSUE TITLE
Dashboard not showing all circuits and wrong thread pool sizes

### ISSUE THREAD

**Issue by jpcaruana** [Netflix/Hystrix#703] opened 2015-03-04 17:09 UTC
Hi, 

I've upgraded hystrix to version 1.3.20, turbine-web to 1.0.0 and my dashboard is very wrong now (it used to work like a charm when I was using hystrix 1.3.19 and turbine-web-0.5.0-SNAPSHOT): 

- many circuits are missing, despite the fact the stream send the right information. Only 2 are on the board and I expect to have 6 of them
- thread pool size is totally wrong: numbers are always growing, not showing reality:

![dashboard](https://cloud.githubusercontent.com/assets/31649/6488455/ff019538-c297-11e4-819c-67ce813634d9.png)

for instance, in reality, the pool PublishToBusCommand is around 400/s on 3 servers.

For circuits, data is arriving from the stream (like this) but not showed  on the dashboard. Here is what I get when I curl one of my servers:

data: {"type":"HystrixCommand","name":"GetResponseCommand","group":"GetResponseCommand","currentTime":1425487780484,"isCircuitBreakerOpen":false,"errorPercentage":0,"errorCount":0,"requestCount":134,"rollingCountCollapsedRequests":0,"rollingCountExceptionsThrown":5,"rollingCountFailure":0,"rollingCountFallbackFailure":0,"rollingCountFallbackRejection":0,"rollingCountFallbackSuccess":0,"rollingCountResponsesFromCache":0,"rollingCountSemaphoreRejected":0,"rollingCountShortCircuited":0,"rollingCountSuccess":141,"rollingCountThreadPoolRejected":0,"rollingCountTimeout":0,"currentConcurrentExecutionCount":0,"latencyExecute_mean":23,"latencyExecute":{"0":0,"25":14,"50":17,"75":24,"90":40,"95":63,"99":172,"99.5":206,"100":246},"latencyTotal_mean":26,"latencyTotal" {"0":0,"25":14,"50":17,"75":24,"90":43,"95":68,"99":300,"99.5":301,"100":527},"propertyValue_circuitBreakerRequestVolumeThreshold":20,"propertyValue_circuitBreakerSleepWindowInMilliseconds":5000,"propertyValue_circuitBreakerErrorThresholdPercentage":50,"propertyValue_circuitBreakerForceOpen":false,"propertyValue_circuitBreakerForceClosed":false,"propertyValue_circuitBreakerEnabled":true,"propertyValue_executionIsolationStrategy":"THREAD","propertyValue_executionIsolationThreadTimeoutInMilliseconds":300,"propertyValue_executionIsolationThreadInterruptOnTimeout":true,"propertyValue_executionIsolationThreadPoolKeyOverride":null,"propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":10,"propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":10,"propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,"propertyValue_requestCacheEnabled":true,"propertyValue_requestLogEnabled":true,"reportingHosts":1}

We see I receive data for the GetResponseCommand circuit, belonging to the GetResponseCommand group. We don't see the circuit on the dashboard, but we see the thread pool (with very wrong data)

**What's wrong with my update ?**

ps: I took a screenshot of my dashboard a few weeks ago, it looked like this (traffic data is higher now):
![hystrix](https://cloud.githubusercontent.com/assets/31649/6488694/73b4280e-c299-11e4-9a97-2c9d50444640.png)

**Comment by jpcaruana** [comment] 2015-03-04 17:14
my config.properties file:

```
turbine.aggregator.clusterConfig=prod
turbine.instanceUrlSuffix=:8080/myapp/hystrix.stream
turbine.ConfigPropertyBasedDiscovery.prod.instances=front-01.mycompany.com,front-02.mycompany.com,front-03.mycompany.com
```

**Comment by mattrjacobs** [comment] 2015-03-04 17:16
Thanks for the report, @jpcaruana.  Now that I've gotten 1.4 out the door, I'm trying to attack the bundle of open dashboard tickets in 1.4.1.  I'll include this as well

**Comment by jpcaruana** [comment] 2015-03-04 17:21
ok thanks @mattrjacobs 
you let me know :)

**Comment by jpcaruana** [comment] 2015-03-04 17:26
hum maybe should I switch to hystrix 1.4.0 ?

**Comment by mattrjacobs** [comment] 2015-03-04 17:28
Here are the 1.4.0 release notes: https://github.com/Netflix/Hystrix/releases/tag/v1.4.0.  I didn't knowingly fix any dashboard bugs, so I'd imagine you'll probably still be in the same broken state w.r.t. the dashboard.  But please feel free to try and report it against 1.4 as well.

**Comment by jpcaruana** [comment] 2015-03-05 10:06
ok thanks.
i've put hystrix 1.4.0 in production and dashboard is still wrong. I'll wait for the 1.4.1 release.

**Comment by mattrjacobs** [comment] 2015-03-05 17:49
Thanks for checking, @jpcaruana.  Will get the dashboard cleaned up as soon as I'm able

**Comment by krzyjab** [comment] 2015-06-17 12:46
For others struggling with this issue, the combination of turbine-web-0.5 and hystrix-dashboard-1.4.3 seems to work correctly. When I tried turbine-web-1.0.0, Hystrix circuits were not showing up and thread pool stats were way off.

**Comment by mattrjacobs** [comment] 2015-06-17 16:27
Thanks for chasing this down, @krzyjab.  I haven't been able to reproduce any data issues with just a server producing Hystrix metrics and a single Hystrix dashboard, so I have suspected Turbine could be involved.  I haven't had time to chase that down, however.

I will link your comment to all the open tickets which may be helped by this find.

**Comment by jpcaruana** [comment] 2015-07-15 09:22
I also tried with turbine-web-0.5 and the last hystrix dashboard: it works fine.

this may look like turbine has a bug

**Comment by mattrjacobs** [comment] 2015-10-15 16:45
Closing this issue, as it looks like root cause is a Turbine bug.

**Closed by mattrjacobs** 2015-10-15 16:45 UTC
Labels: bug, dashboard
