### ISSUE TITLE
The real exception is hidden when an unexpected exception is thrown in a fallback, and the cause is null

### ISSUE THREAD

**Issue by jorgefr** [Netflix/Hystrix#1313] opened 2016-08-09 13:03 UTC
In the specified line of GenericCommand, any `Throwable` being thrown by the fallback is supposed to be logged:

https://github.com/Netflix/Hystrix/blob/f918595cf2fed44c9e1706abe4b55d73d80f31e9/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/GenericCommand.java#L79

But in the `exception()` method of `FallbackErrorMessageBuilder` only `HystrixBadRequestException` and `HystrixRuntimeException` are being logged:

https://github.com/Netflix/Hystrix/blob/f918595cf2fed44c9e1706abe4b55d73d80f31e9/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/AbstractHystrixCommand.java#L227

Going back to GenericCommand, after the logging sentence, the cause of the exception is wrapped (not the exception itself): `throw new FallbackInvocationException(e.getCause());` The problem is that the cause might be null quite often.

Even if an implementation of `HystrixCommandExecutionHook#onFallbackError` is provided, there is nothing useful from the original exception, so the real cause of the exception is hidden everywhere.

Is there any other place where the real exception can be managed?

**Comment by mattrjacobs** [comment] 2016-08-10 23:07
I don't know enough about specifically how `hystrix-javanica` does error-handling.  @dmgcodevil - can you take a look?

**Comment by dmgcodevil** [comment] 2016-08-21 15:12
@mattrjacobs, I'm looking into it.

**Comment by dmgcodevil** [comment] 2016-08-21 20:53
@jorgefr, Currently it's possible only to get the exception thrown within command method, no way to get an exception thrown within fallback. Essentially you get cause exception i.e. first one thrown from command that basically triggers fallback execution, it's docummented [here](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-javanica). Consider the following test:

```java
public class IssTest extends BasicHystrixTest {

    @Autowired
    private Service service;

    @Test(expected = CommandException.class)
    public void test() {
        service.command();
    }

    public static class Service {
        @HystrixCommand(fallbackMethod = "fallback")
        public Object command() {
            throw new CommandException();
        }
        @HystrixCommand
        public Object fallback() {
            throw new FallbackException();
        }
    }

    private static class CommandException extends RuntimeException {}

    private static class FallbackException extends RuntimeException {}

    @Configurable
    public static class Config {
        @Bean
        public Service service() {
            return new Service();
        }
    }
}
```

It's hard to justify that fallback exception is more important for user than command exception, ideally it would be great to get both, but it's not possible without custom exception that will combine both: command and fallback.

before https://github.com/Netflix/Hystrix/issues/993 all exceptions were wrapped in HystrixBadRequestException. The reason why this logic was removed is that users want to get real exception, for more details/reasons see the issue. Probably we can extend ```HystrixCommand``` annotation in order to add some hook there, for instance: 

```java
@HystrixCommand(onFallbackError="onErrorMethod")
...
void onErrorMethod(Exception e) {
 // process fallback exception here
}
```

I understand the importance of this issue because it's crucial from design perspective but haven't found a way how to solve this problem in an elegant way. Thoughts?


cc / @Geniy00, @hacbq, @shakuzen

**Comment by jorgefr** [comment] 2016-08-23 09:32
@dmgcodevil thanks for your reply.

I agree that the important exception is the one in the command. In fact I've read in your docs that it is a good practice not to throw any exception within the fallback and we are trying to follow that convention. But in my case, there was an unexpected exception that wasn't being showing anywhere.

As you point out, in that test, the exception is logged because the fallback is a `HystrixCommand` itself and it is wrapped as the cause in a `HystrixRuntimeException`, and, in addition, it will be handed over to the `HystrixCommandExecutionHook`. But I don't think that converting all our fallbacks to a `HystrixCommand` only to get the exception logged is the best option.

I don't know all the code and the consequences but, 

could the method https://github.com/Netflix/Hystrix/blob/f918595cf2fed44c9e1706abe4b55d73d80f31e9/hystrix-contrib/hystrix-javanica/src/main/java/com/netflix/hystrix/contrib/javanica/command/AbstractHystrixCommand.java#L227 log also the stack trace of any kind of exception different from`HystrixBadRequestException` and `HystrixRuntimeException`? 

It shouldn't be too spammy, since the fallback is not supposed to throw exceptions, right?

**Comment by dmgcodevil** [comment] 2016-08-23 13:18
@jorgefr yes, it's fine and easy to fix the logging logic. Will do it. We can create separate issue to add some hook for getting an exception thrown by fallback.

**Comment by jorgefr** [comment] 2016-09-02 08:52
Ok. Thanks!

Do I need to create the other issue?

**Comment by dmgcodevil** [comment] 2016-09-02 17:41
@jorgefr I believe it's created already https://github.com/Netflix/Hystrix/issues/1344 so join to discussion because we need design it in a way to satisfy all clients requirements.

**Comment by mattrjacobs** [comment] 2016-09-16 22:32
Any concerns if i close this ticket and mark it as a duplicate of #1344?

**Comment by jorgefr** [comment] 2016-09-19 20:43
Not from my side

**Closed** 2016-10-19 21:21 UTC
Labels: bug, javanica, question
